### Section A : Data Structures & Control Structures

##### 1. Create a list of 5 integer. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [20]:
list1 = [23,56,78,45,34]

In [21]:
print("List of Integer Value:",list1)

List of Integer Value: [23, 56, 78, 45, 34]

In [22]:
list1.append(67)
print("List After append :",list1)

List After append : [23, 56, 78, 45, 34, 67]

In [23]:
list1.extend([70, 80])
print("After extend([70, 80]):", list1)

After extend([70, 80]): [23, 56, 78, 45, 34, 67, 70, 80]

In [24]:
list1.insert(24,60)
print("List after inserting two values :",list1)

List after inserting two values : [23, 56, 78, 45, 34, 67, 70, 80, 60]

In [25]:
list1.pop()
print("List after pop operation:",list1)

List after pop operation: [23, 56, 78, 45, 34, 67, 70, 80]

In [26]:
list1.remove(34)
print("List after removing 34:",list1)

List after removing 34: [23, 56, 78, 45, 67, 70, 80]

In [27]:
print("Total Count of 23:", list1.count(23))

Total Count of 23: 1

In [28]:
print("Index of 78:",list1.index(78))

Index of 78: 2

In [29]:
list1.sort()
print("Sorted List:",list1)

Sorted List: [23, 45, 56, 67, 70, 78, 80]

In [30]:
list1.reverse()
print("Reversed  List:",list1)

Reversed  List: [80, 78, 70, 67, 56, 45, 23]

In [31]:
list1.clear()
print("After clearing he list:",list1)

After clearing he list: []

#### 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [32]:
students = ("Sneha","Sidhhesh","Shravya") #create tuple with 3 values
print(students)

('Sneha', 'Sidhhesh', 'Shravya')

In [33]:
students[1]= "Satvik" # it showing the error because tuple is immutable. we cant change the values
print("Display the updated tuple :", students)

TypeError: 'tuple' object does not support item assignment

#### 3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [ ]:
set1 = {12,34,56,11,12,51,78,34,11}
print(set1)

set1 is a set which stores only unic values... It removes duplicate values.. also not showing the output in perticular order not in sorted order and not as per the sequence we added in the set1.. it uses hashing soo elements display in random order

#### 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [ ]:
dict1 ={
    "name" : "Sneha",
    "age" : 28,
    "City" : "Pune"
}
print("Dictionary:",dict1)

In [ ]:
dict1["age"]=26  #here update the value of age to 26
print("Dictionary After updating Age value:",dict1)

In [ ]:
dict1["email"] = "snehass@gmail.com"
print("Dictionary After adding key 'email':",dict1)

In [ ]:
for key, values in dict1.items():
    print(key ,":", values)

#### 5.  Write a script that checks if a person is eligible to vote (age = 18). Take age as a variable and print the appropriate message.

In [ ]:
age = int(input("Enter age :"))
if age>18:
    print("Person is eligible to vote")
else:
    print("Person is not eligible to vote")

#### 6. Given a 'marks' variable, print the grade:
#### - 90 and above: 'A'
#### - 75-89: 'B'
#### - 50-74: 'C'
#### - Below 50: 'Fail'

In [35]:
marks = int(input("Enter marks:"))
if marks > 90:
    print("Student Pass with Grade : A")
elif marks > 75 & marks < 89:
    print("Student Pass with Grade : B")
elif marks > 50 & marks <74:
    print("Student Pass with Grade : C")
elif marks < 50:
    print("Student is Fail")
else:
    print("Please enter valid percentage")

Enter marks: 65

Student Pass with Grade : C

#### 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [61]:
num = int(input("Enter number"))

if num ==0:
    print("Number is zero")
elif num>0:
    print("number is Positive")
    if num%2==0:
        print("Even Number")   
else:
    print("Number is Negative")

Enter number 22

number is Positive
Even Number

## Section B: Numpy

##### 8. Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [62]:
import numpy as np
a = np.array(5)
print(a)
print(type(a))

5
<class 'numpy.ndarray'>

In [63]:
array = [1,2,3,4,5]
print(array)

[1, 2, 3, 4, 5]

In [70]:
array1 = np.arange(10,70,10).reshape(2,3)
print(array1)

[[10 20 30]
 [40 50 60]]

#### 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [73]:
arr = np.random.randint(1,100,16).reshape(4,4)
print(arr)

[[20 32 93 13]
 [41 15 96 44]
 [72 17  5 69]
 [44 47 36 88]]

#### 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [78]:
import pandas as pd
arr = np.random.randint(1,100,9).reshape(3,3)
df=pd.DataFrame(arr,columns=('A','B','C'))
print(df)

    A   B   C
0  79  43  40
1  96   3  57
2  55  39  19

### Section C: Exploring Pandas

#### 11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
##### - Use .info(), .describe()
##### - Select 'Name' and 'City' columns
##### - Drop 'City' column
##### - Fill any missing values in 'Salary' column with the mean
##### - Remove any duplicate rows

In [118]:
data = {
    'Name' : ["Sneha","Satvik","Shravya","Sidhhesh","Shubham",
              'Vaishanvi','Vrushali','Pallavi','Priya','Prajwal'],
    'Age'  : [28,24,26,29,24,34,27,26,25,34],
    'City' : ['Pune','Mumbai','Pune','Delhi','Pune',
              'pune','Mumbai','pune','pune','Delhi'],
    'Salary': [25000,34000,None,27000,25000,
               30000,28000,None,25000,20000]
}
df = pd.DataFrame(data)
print(df)

        Name  Age    City   Salary
0      Sneha   28    Pune  25000.0
1     Satvik   24  Mumbai  34000.0
2    Shravya   26    Pune      NaN
3   Sidhhesh   29   Delhi  27000.0
4    Shubham   24    Pune  25000.0
5  Vaishanvi   34    pune  30000.0
6   Vrushali   27  Mumbai  28000.0
7    Pallavi   26    pune      NaN
8      Priya   25    pune  25000.0
9    Prajwal   34   Delhi  20000.0

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [120]:
df.describe()

             Age        Salary
count  10.000000      8.000000
mean   27.700000  26750.000000
std     3.683296   4131.758533
min    24.000000  20000.000000
25%    25.250000  25000.000000
50%    26.500000  26000.000000
75%    28.750000  28500.000000
max    34.000000  34000.000000

In [121]:
df

        Name  Age    City   Salary
0      Sneha   28    Pune  25000.0
1     Satvik   24  Mumbai  34000.0
2    Shravya   26    Pune      NaN
3   Sidhhesh   29   Delhi  27000.0
4    Shubham   24    Pune  25000.0
5  Vaishanvi   34    pune  30000.0
6   Vrushali   27  Mumbai  28000.0
7    Pallavi   26    pune      NaN
8      Priya   25    pune  25000.0
9    Prajwal   34   Delhi  20000.0

In [122]:
df[['Name','City']]

        Name    City
0      Sneha    Pune
1     Satvik  Mumbai
2    Shravya    Pune
3   Sidhhesh   Delhi
4    Shubham    Pune
5  Vaishanvi    pune
6   Vrushali  Mumbai
7    Pallavi    pune
8      Priya    pune
9    Prajwal   Delhi

In [123]:
df= df.drop('City',axis=1)
df

        Name  Age   Salary
0      Sneha   28  25000.0
1     Satvik   24  34000.0
2    Shravya   26      NaN
3   Sidhhesh   29  27000.0
4    Shubham   24  25000.0
5  Vaishanvi   34  30000.0
6   Vrushali   27  28000.0
7    Pallavi   26      NaN
8      Priya   25  25000.0
9    Prajwal   34  20000.0

In [124]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df[['Salary']]

    Salary
0  25000.0
1  34000.0
2  26750.0
3  27000.0
4  25000.0
5  30000.0
6  28000.0
7  26750.0
8  25000.0
9  20000.0